DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
  id IDENTITY,
  title VARCHAR(500)
);

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR (
  id IDENTITY,
  name VARCHAR(500)
);

DROP TABLE IF EXISTS BOOK_AUTHOR;
CREATE TABLE BOOK_AUTHOR (
  book INTEGER,
  author INTEGER
);