DROP TABLE IF EXISTS PURCHASE_ORDER;
CREATE TABLE PURCHASE_ORDER (
  id         IDENTITY,
  shipping_address VARCHAR(500)
);

DROP TABLE IF EXISTS ORDER_ITEM;
CREATE TABLE ORDER_ITEM (
  purchase_order INTEGER,
  product VARCHAR(500),
  quantity INTEGER
);